### ISSUE TITLE
create a form to report an issue

### ISSUE THREAD

**Issue by shyams** [HSH-Global/fixmystreet#10]
![reportform](https://cloud.githubusercontent.com/assets/1906434/6229877/a2678b8c-b6c3-11e4-9457-66929e616169.png)

Create a form like above picture
1) On click on categories should get a list of categories.
2)  Description field to give description about the issue.
3) On click on picture button should open the camera or gallery to select picture
4) Location button should capture the current location. Should display the full address

**Work-flow**
1) Create a event folder `reportissue` in `evently > reportandfix`
2) Trigger this event folder from `evently > reportandfix > _init > selectors` (use id as selector)
3) Create a view `issueCategories` with reduce function which should emit issue categories.
4) Create `async.js`, in event folder `reportissue` and get the data required for categories using the view.
5) Create `data.js`, in event folder `reportissue`  and prepare the data you got from `async`
6) Create the  `mustache.html` in event folder `reportissue` to display the form.
7) on submit should save the issue in db. And have to trigger to event `issuedetail` with  `issue _id` as params.

**Note:** issue number is a just a random 6 digit number

Below is the issue doc format
```json
{
   "_id": "4858c8d440051bd24d146147a806a3e0",
   "type": "issue",
   "number": "275222",
   "lat": "-32.904455",
   "lng": "17.992382",
   "place": "8 Dorp St, Vredenburg 7380, South Africa",
   "area_name": "Vredenburg North, Green Village & Langebaanweg",
   "area_id": "4858c8d440051bd24d146147a801cac9",
   "usr_name": "Bhekithemba Mbou",
   "usr_id": "bhekim",
   "cat_id": "4858c8d440051bd24d146147a800a5a4",
   "cat_name": "Dumping",
   "title": "Roadworks barriers",
   "desc": "This roadwork is too close to the community and can cause accidents",
   "opened_at": "2014-08-14T15:00:10+00:00",
   "channel": "publicpointer",
   "_attachments": {
       "issue-275222.jpeg": {
           "content_type": "image/jpeg",
           "revpos": 2,
           "digest": "md5-+962oSD1OaqQ1YPB49k4Kg==",
           "length": 699107,
           "stub": true
       }
   }
}
```

**Comment by diderson** [comment]
@shyams I think this Issue should have been breakdown into two or three parts.

1. displaying the form and get it ready to be saved
2. doing the save function

Please on your image you forgot the title of the issue
P.S I think the idea is not to have so may files modified so the review will be easy
