### ISSUE TITLE
Remove css borders for list

### ISSUE THREAD

**Issue by shyams** [HSH-Global/fixmystreet#24]
![border](https://cloud.githubusercontent.com/assets/1906434/6324095/762b43be-bb3d-11e4-928a-7dde39aa2c15.png)

In the above image there is a border with `border: 1px solid #ddd;`. Remove border top and bottom for first and last child. And remove border left and right for whole list.

**Comment by faithze** [comment]
@shyams this is how this thing looks with out the ```border:1px solid #ddd``` is this how you want it to look?

![untitled-1](https://cloud.githubusercontent.com/assets/6327993/6324296/c603d7c2-bb40-11e4-915c-3f62190a15bb.png)
