### ISSUE TITLE
Display issues in map

### ISSUE THREAD

**Issue by shyams** [HSH-Global/fixmystreet#27]
Display all the issues on the map.

**Work-flow**
1) Create a new event name `issueonthemap` in `evently/reportandfix`.
3) Create `after.js` and get all issues `lat lon`
3) Display the markers at issues `lat lon` positions in the  map.

**Comment by diderson** [comment]
@shyam I think the event name should be "issuemap" or  "issueonthemap" something that will be clear to help us in future for matainance.



<div>-------- Original message --------</div><div>From: shyamsunder <notifications@github.com> </div><div>Date:23/02/2015  14:18  (GMT+02:00) </div><div>To: HSH-Global/fixmystreet <fixmystreet@noreply.github.com> </div><div>Subject: [fixmystreet] Display issues in map (#27) </div><div>
</div>Display all the issues on the map.

Work-flow
1) Create a new event name mapview in evently/reportandfix.
3) Create after.js and get all issues lat lon
3) Display the markers at issues lat lon positions in the map.

**Comment by shyams** [comment]
@diderson ok i agree,  we will change as per your suggestion
